import { Opportunity } from './types'

export const mockOpportunities: Opportunity[] = [
  {
    id: '1',
    title: 'Contratação de Consultoria Especializada em TI',
    number: '001/2026',
    organ: 'Ministério da Fazenda',
    modality: 'Pregão Eletrônico',
    status: 'Em Análise',
    verdict: 'Pendente',
    score: 0,
    dateAdded: '2026-07-10T10:00:00Z',
    dueDate: '2026-08-15T09:00:00Z',
    openingDate: '2026-08-15T09:00:00Z',
    state: 'DF',
    city: 'Brasília',
    portal: 'https://www.gov.br/compras',
    responsible: 'Carlos Eduardo',
    observations: 'Edital publicado no DOU de 09/07/2026.',
    radarSynced: false,
  },
  {
    id: '2',
    title: 'Estudo de Viabilidade para Porto Seco',
    number: '045/2026',
    organ: 'Governo do Estado',
    modality: 'Concorrência',
    status: 'Entrar',
    verdict: 'Entrar',
    score: 92,
    dateAdded: '2026-07-08T14:30:00Z',
    dueDate: '2026-08-01T10:00:00Z',
    openingDate: '2026-08-01T10:00:00Z',
    state: 'SP',
    city: 'São Paulo',
    portal: 'https://www.bec.sp.gov.br',
    responsible: 'Carlos Eduardo',
    observations: 'Oportunidade estratégica alinhada ao portfólio da Hebron.',
    radarSynced: true,
    estimatedMargin: 22,
  },
  {
    id: '3',
    title: 'Auditoria de Processos Licitatórios',
    number: '012/2026',
    organ: 'Prefeitura Municipal',
    modality: 'Tomada de Preços',
    status: 'Analisar Mais',
    verdict: 'Analisar Mais',
    score: 65,
    dateAdded: '2026-07-09T09:15:00Z',
    dueDate: '2026-07-15T14:00:00Z',
    openingDate: '2026-07-15T14:00:00Z',
    state: 'MG',
    city: 'Belo Horizonte',
    portal: 'https://www.portaldecompras.com',
    responsible: 'Ana Paula',
    observations: 'Verificar requisitos de equipe técnica mínima.',
    radarSynced: true,
    estimatedMargin: 18,
  },
  {
    id: '4',
    title: 'Plano Diretor de Tecnologia da Informação',
    number: '089/2026',
    organ: 'Tribunal de Justiça',
    modality: 'Pregão Eletrônico',
    status: 'Não Entrar',
    verdict: 'Não Entrar',
    score: 30,
    dateAdded: '2026-07-05T11:45:00Z',
    dueDate: '2026-07-13T08:30:00Z',
    openingDate: '2026-07-13T08:30:00Z',
    state: 'RJ',
    city: 'Rio de Janeiro',
    portal: 'https://www.licitacoes-e.com',
    responsible: 'Carlos Eduardo',
    observations: 'CNAE incompatível e segmento excluído.',
    radarSynced: true,
  },
  {
    id: '5',
    title: 'Mapeamento de Riscos e Compliance',
    number: '102/2026',
    organ: 'Banco Central',
    modality: 'Concorrência',
    status: 'Documentação Incompleta',
    verdict: 'Pendente',
    score: 0,
    dateAdded: '2026-07-11T08:00:00Z',
    dueDate: '2026-09-01T10:00:00Z',
    openingDate: '2026-09-01T10:00:00Z',
    state: 'DF',
    city: 'Brasília',
    portal: 'https://www.gov.br/compras',
    responsible: 'Ana Paula',
    observations: 'Apenas aviso de contratação publicado. Análise preliminar.',
    radarSynced: false,
  },
]
