import { AnalysisResult, DecisionQuestion } from './types'

export const analysisById: Record<string, AnalysisResult> = {
  '2': {
    scoreItems: [
      { label: 'Compatibilidade CNAE', points: 20, max: 20, source: 'Edital pág. 8' },
      { label: 'Segmento Estratégico', points: 15, max: 15, source: 'Edital pág. 3' },
      { label: 'Benefício ME/EPP', points: 10, max: 10, source: 'Edital pág. 15' },
      { label: 'Certificações Viáveis', points: 10, max: 10, source: 'Edital pág. 22' },
      { label: 'Modalidade Fast-track', points: 10, max: 10, source: 'Edital pág. 1' },
      { label: 'Sem Exigência de Estoque', points: 10, max: 10, source: 'TR pág. 5' },
      { label: 'Valor ≤ R$ 200k', points: 0, max: 5, source: 'Edital pág. 12' },
      { label: 'Sem Garantia/Garantia Baixa', points: 2, max: 5, source: 'Minuta Cláusula 7' },
      { label: 'Entrega Regional/Remota', points: 10, max: 10, source: 'TR pág. 8' },
      { label: 'Habilitação Padrão', points: 5, max: 5, source: 'Edital pág. 18' },
    ],
    scoreTotal: 92,
    items: [
      {
        id: '1',
        name: 'Consultoria em Gestão de Projetos',
        quantity: 1200,
        unit: 'horas',
        estimatedValue: 150,
        source: 'TR pág. 3',
      },
      {
        id: '2',
        name: 'Desenvolvimento de Software Sob Medida',
        quantity: 800,
        unit: 'horas',
        estimatedValue: 200,
        source: 'TR pág. 4',
      },
      {
        id: '3',
        name: 'Análise de Dados e BI',
        quantity: 500,
        unit: 'horas',
        estimatedValue: 180,
        source: 'TR pág. 5',
      },
      {
        id: '4',
        name: 'Sustentação de Sistemas',
        quantity: 12,
        unit: 'meses',
        estimatedValue: 35000,
        source: 'TR pág. 6',
      },
      {
        id: '5',
        name: 'Treinamento de Equipes',
        quantity: 40,
        unit: 'turmas',
        estimatedValue: 2500,
        source: 'TR pág. 7',
      },
      {
        id: '6',
        name: 'Documentação Técnica',
        quantity: 10,
        unit: 'unidades',
        estimatedValue: 5000,
        source: 'TR pág. 8',
      },
      {
        id: '7',
        name: 'Auditoria de Segurança',
        quantity: 4,
        unit: 'unidades',
        estimatedValue: 15000,
        source: 'TR pág. 9',
      },
      {
        id: '8',
        name: 'Suporte Técnico Nível 1',
        quantity: 2000,
        unit: 'horas',
        estimatedValue: 80,
        source: 'TR pág. 10',
      },
    ],
    risks: [
      {
        category: 'Jurídico',
        description: 'Garantia contratual de 5% sobre o valor global.',
        severity: 'medium',
        source: 'Minuta Cláusula 7',
      },
      {
        category: 'Documental',
        description: 'Atestados de capacidade técnica exigem projetos similares.',
        severity: 'low',
        source: 'Edital pág. 20',
      },
      {
        category: 'Técnico',
        description: 'Equipe sênior presencial exigida (2 profissionais).',
        severity: 'medium',
        source: 'TR pág. 12',
      },
      {
        category: 'Operacional',
        description: 'Prazo de implantação de 30 dias após assinatura.',
        severity: 'medium',
        source: 'TR pág. 15',
      },
      {
        category: 'Financeiro',
        description: 'Penalidades de 0,5% por dia de atraso (limite 10%).',
        severity: 'high',
        source: 'Minuta Cláusula 9',
      },
      {
        category: 'Comercial',
        description: 'Modelo de UST pode dificultar precificação competitiva.',
        severity: 'low',
        source: 'TR pág. 3',
      },
    ],
    alerts: [
      {
        clause: 'Cláusula 12.3',
        description:
          'Exige certificação ISO 27001 específica para o projeto, potencialmente restritiva.',
        deadline: '25/07/2026 18:00',
        source: 'Edital pág. 22',
      },
      {
        clause: 'Anexo IV §2',
        description: 'Direcionamento de marca em software de BI.',
        deadline: '25/07/2026 18:00',
        source: 'Edital pág. 30',
      },
    ],
    checklist: [
      {
        name: 'Balanço Patrimonial atualizado',
        category: 'Qualificação Econômica',
        mandatory: true,
        status: 'ok',
        source: 'Edital pág. 18',
      },
      {
        name: 'Certidão Negativa Trabalhista (CNDT)',
        category: 'Habilitação Jurídica',
        mandatory: true,
        status: 'ok',
        source: 'Edital pág. 17',
      },
      {
        name: 'Atestados de Capacidade Técnica (mín 2)',
        category: 'Qualificação Técnica',
        mandatory: true,
        status: 'ok',
        source: 'Edital pág. 20',
      },
      {
        name: 'Certidão Negativa Federal',
        category: 'Habilitação Jurídica',
        mandatory: true,
        status: 'ok',
        source: 'Edital pág. 17',
      },
      {
        name: 'Declaração de Sustentabilidade',
        category: 'Declarações',
        mandatory: false,
        status: 'pending',
        source: 'Edital pág. 25',
      },
      {
        name: 'Comprovação de ISO 27001',
        category: 'Qualificação Técnica',
        mandatory: true,
        status: 'missing',
        source: 'Edital pág. 22',
      },
    ],
    summary:
      'O edital visa a contratação de empresa especializada para prestação de serviços de consultoria em TI, englobando desenvolvimento de software, sustentação e análise de dados. Valor estimado de R$ 4.500.000,00 com vigência de 24 meses.',
    technicalAnalysis:
      'O objeto é altamente aderente ao portfólio da Hebron. O modelo de precificação por UST é favorável, e o acervo técnico exigido está dentro da capacidade comprovada. Não há exigência de certificações internacionais exclusivas.',
    recommendations:
      'Recomenda-se formar consórcio caso a garantia contratual impacte o fluxo de caixa. Iniciar imediatamente a preparação da documentação técnica e jurídica. Prazo revisão jurídica: até 05/08/2026.',
    estimatedMargin: 22,
    documentClassification: 'Completo',
    eliminationLocks: [],
  },
  '4': {
    scoreItems: [
      { label: 'Compatibilidade CNAE', points: 0, max: 20, source: 'CNAE incompatível' },
      {
        label: 'Segmento Estratégico',
        points: 0,
        max: 15,
        source: 'Segmento excluído: Engenharia Pesada',
      },
      { label: 'Benefício ME/EPP', points: 10, max: 10, source: 'Edital pág. 15' },
      { label: 'Certificações Viáveis', points: 5, max: 10, source: 'Edital pág. 22' },
      { label: 'Modalidade Fast-track', points: 10, max: 10, source: 'Edital pág. 1' },
      { label: 'Sem Exigência de Estoque', points: 5, max: 10, source: 'TR pág. 5' },
      { label: 'Valor ≤ R$ 200k', points: 0, max: 5, source: 'Edital pág. 12' },
      { label: 'Sem Garantia/Garantia Baixa', points: 0, max: 5, source: 'Minuta Cláusula 7' },
      { label: 'Entrega Regional/Remota', points: 0, max: 10, source: 'TR pág. 8' },
      { label: 'Habilitação Padrão', points: 0, max: 5, source: 'Edital pág. 18' },
    ],
    scoreTotal: 30,
    items: [],
    risks: [
      {
        category: 'Jurídico',
        description: 'CNAE incompatível com o ramo de atuação da Hebron.',
        severity: 'high',
        source: 'Edital pág. 8',
      },
      {
        category: 'Técnico',
        description: 'Segmento excluído: Engenharia Pesada.',
        severity: 'high',
        source: 'Edital pág. 3',
      },
    ],
    alerts: [],
    checklist: [],
    summary:
      'Edital bloqueado automaticamente: CNAE incompatível e segmento excluído (Engenharia Pesada). Não prosseguir com a análise.',
    technicalAnalysis: 'N/A — Bloqueio eliminatório aplicado.',
    recommendations: 'Não entrar. Documentar motivo para aprendizado futuro.',
    estimatedMargin: 0,
    documentClassification: 'Completo',
    eliminationLocks: ['CNAE incompatível', 'Segmento excluído: Engenharia Pesada'],
  },
}

export const decisionGateById: Record<string, DecisionQuestion[]> = {
  '2': [
    {
      id: 1,
      question: 'Existe bloqueio eliminatório?',
      answer: false,
      autoFilled: true,
      hint: 'Verificado automaticamente pela análise de IA',
    },
    {
      id: 2,
      question: 'Há tempo suficiente para preparação?',
      answer: true,
      autoFilled: true,
      hint: 'Configurado: mínimo de 3 dias úteis',
    },
    {
      id: 3,
      question: 'Todos os documentos estão disponíveis?',
      answer: false,
      autoFilled: true,
      hint: 'Baseado no checklist documental (1 obrigatório faltante)',
    },
    {
      id: 4,
      question: 'A margem estimada supera o mínimo (15%)?',
      answer: true,
      autoFilled: false,
      hint: 'Margem estimada: 22%',
    },
    {
      id: 5,
      question: 'Temos capacidade operacional?',
      answer: null,
      autoFilled: false,
      hint: 'Avaliação do gestor',
    },
  ],
}
